analyze_code_task:
  description: >
    Analyze the code in the specified GitHub repository to identify potential issues and areas for improvement.
  expected_output: >
    A detailed report highlighting the identified issues and suggested improvements.
  agent: code_analyzer

improve_code_task:
  description: >
    Make improvements to the code in the specified GitHub repository based on the analysis report.
  expected_output: >
    Improved code committed to the GitHub repository.
  agent: code_improver

respond_query_task:
  description: >
    Answer questions about the codebase and provide detailed explanations.
  expected_output: >
    Detailed answers and insights about the codebase.
  agent: query_responder
